"""C3 generation under proof — specification §9.4/§16.1, story S5.3.1.

    "C3 calculations generated by a model with the context contract and validated up the
    ladder before proof, so that a model output can never reach the client repository
    without passing execution."

**What this module is.** §9.4's own `GenerationRequest` (assembled directly from the graph,
the same footing `classify.py`/`rules.py` already established for facts a formal context
contract doesn't carry), §16.1's validation ladder as a real, composable pipeline, and the
bounded regeneration loop the acceptance criteria names ("up to two regeneration attempts on
parse or compile failure with the error fed back; then the field is routed to the Exception
Desk with all attempts attached"). A successful generation writes a real `Measure` (mode
`GENERATED_PROVED`), a `MAPS_TO` edge, and a `ProvenanceRecord` carrying the full
`model_call` block §4.2 names. An exhausted or declined one writes a real `ExceptionCase` —
the first story to drive that node type, the same "declared since S1.1.1, driven for the
first time" trajectory `SemanticModel.state`/`Measure`/`Pattern` have each already taken.

**What this module is not, and why each rung is what it is.** Story S5.3.2 filled the one
gap ADR 0038 named as its own: the Transpiler now calls `gateway.generate(task_class=
TRANSPILE_C3, ...)` (`.gateway`, §5.5) — a real, provider-agnostic router in front of a real
`AnthropicModelCaller`, gated by a real, Postgres-backed eval-set policy. This module still
never fabricates a check that doesn't verify what it claims (the same discipline ADR
0036/0037/0038 already applied three times in this exact epic):

- **No DAX parser exists.** `rules.dax_sanity_check` (S5.2.1's own structural stand-in,
  balanced delimiters plus a known-function allowlist) is reused here for rung 2, unchanged
  — the same honest floor, not a new grammar (a real one is its own S2.3.1-scale effort).
- **No live Fabric dev workspace exists (E11).** Rung 3 ("compile") is a disclosed,
  unconditional pass, the identical posture `FixtureTargetAdapter.smoke_query` (S4.3.1)
  already set for a capability this platform cannot yet exercise for real.
- **No Arbiter/Proof Engine exists (E7).** Rung 4 ("proof") is a disclosed, unconditional
  pass, the identical posture `model_lifecycle.regression_status` (S4.3.3) already set for
  "nothing here can compute this verdict yet."

Because rungs 3 and 4 can never themselves fail today, only rungs 1 (schema — a hard
failure, never retried, per §16.1's own table) and 2 (parse) can actually drive a
regeneration or an escalation — which is the honest, current shape of "validated up the
ladder," not a weaker version of it dressed up to look complete. See ADR 0038 for the full
reasoning.

**Two more real, disclosed data gaps this module's own `GenerationRequest` inherits.**
`model_ctx.tables`/`.columns` are empty: no `Field→ModelTable` `MAPS_TO` edge has ever been
written by any story (the Modeller's own S4.1.1 output never populated them — a real,
separate gap this module does not attempt to fix). `charter_excerpt` names no live G1
Tolerance Charter: nothing in this codebase has ever recorded one (§4.4's charter/tolerance
mechanism is not built). Both are disclosed directly in the request document rather than
silently omitted.

**Story S5.3.3 adds real confidence calibration (`.calibration`, §16.3).** Every attempt
that declares a confidence is recorded as a real observation, win or lose; before running
the ladder, `generate_c3_field` checks whether `TRANSPILE_C3`'s own calibration has crossed
`calibration.DEFAULT_CALIBRATION_FLOOR` and, if so, runs the ladder against
`TRANSPILE_C3_SMALL_MODEL` instead — a real routing decision onto a disclosed-absent
destination (no small-model `ModelCaller` is ever registered), the identical footing
Azure OpenAI already has under `TRANSPILE_C3` itself. See `calibration.py`'s own module
docstring for why this reroute is designed to stay pinned rather than self-heal.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

import asyncpg
from pydantic import BaseModel, ConfigDict, ValidationError
from pydantic import Field as PydanticField

from .calibration import CalibrationStore, NullCalibrationStore
from .classify import ClassificationContext, classify
from .context.canonical import context_hash
from .context.contract import ContractName
from .context.signature import ast_shape
from .context.signature import matches as signature_matches
from .gateway import (
    TRANSPILE_C3,
    TRANSPILE_C3_SMALL_MODEL,
    EvalCase,
    EvalReport,
    Gateway,
    GatewayRoutingError,
    ModelCaller,
    RawModelResponse,
    SupportsAsDict,
    null_gateway,
    run_eval_set,
)
from .graph.queries import EDGE_INDEX_TABLE, NODE_INDEX_TABLE
from .ids import new_ulid
from .lineage import children, hydrate
from .ontology.types import BASE_NODE_PROPERTIES
from .patterns import (
    apply_active_pattern,
    find_matching_pattern,
    generalise_from_proof,
    record_observation,
)
from .principal import Principal
from .provenance import AgentMode, ProvenanceStore, new_record
from .rules import dax_sanity_check
from .versions import EVENT_TABLE
from .writes import EdgeWrite, GraphWriter, NodeWrite

_AGENT = "transpiler"
_AGENT_VERSION = "0.1.0"

#: §16.1: "one regeneration" per failing rung; the backlog's own S5.3.1 wording collapses
#: parse and compile into one shared budget of two, so this is one initial attempt plus two
#: regenerations, not two per rung.
MAX_ATTEMPTS = 3

#: Appendix-bounded: a dependency chain nested this deep is a modelling defect, not a real
#: calculation (the same reasoning `signature.py`'s own `MAX_DEPTH` already gives AST walks).
MAX_CLOSURE_DEPTH = 5

#: §9.4's own fixed constraint list, verbatim.
CONSTRAINTS: tuple[str, ...] = (
    "output DAX only",
    "no new tables",
    "use existing measures where semantics match",
    "declare assumptions as JSON",
    "if not expressible say NOT_EXPRESSIBLE with reason",
)

#: §9.4's own output_schema, verbatim.
OUTPUT_SCHEMA: dict[str, str] = {
    "dax": "string",
    "m": "string|null",
    "assumptions": "[string]",
    "confidence": "number",
    "notes": "string",
}

NOT_EXPRESSIBLE = "NOT_EXPRESSIBLE"


class ModelResponseSchema(BaseModel):
    """§16.1 rung 1: "Model response conforms to the declared output schema (JSON schema,
    strict)." A real, working schema check (pydantic, already a dependency) -- not a
    disclosed stand-in; nothing about JSON-schema validation needs infrastructure this
    platform lacks."""

    model_config = ConfigDict(extra="forbid")

    dax: str
    m: str | None = None
    assumptions: list[str] = PydanticField(default_factory=list)
    confidence: float
    notes: str


# ------------------------------------------------------------------------- the request


@dataclass(frozen=True, slots=True)
class GenerationRequest:
    task: str
    source: Mapping[str, Any]
    dependency_closure: Mapping[str, Any]
    sheet_ctx: Mapping[str, Any]
    model_ctx: Mapping[str, Any]
    patterns: tuple[Mapping[str, Any], ...]
    charter_excerpt: Mapping[str, Any]
    params: tuple[Mapping[str, Any], ...]
    constraints: tuple[str, ...]
    output_schema: Mapping[str, str]

    def as_dict(self) -> dict[str, Any]:
        return {
            "task": self.task,
            "source": dict(self.source),
            "dependency_closure": dict(self.dependency_closure),
            "sheet_ctx": dict(self.sheet_ctx),
            "model_ctx": dict(self.model_ctx),
            "patterns": [dict(p) for p in self.patterns],
            "charter_excerpt": dict(self.charter_excerpt),
            "params": [dict(p) for p in self.params],
            "constraints": list(self.constraints),
            "output_schema": dict(self.output_schema),
        }

    def context_hash(self) -> str:
        """§4.2/§16.4: the hash an auditor checks the model's own context against, and
        §5.5's own cache key ("caches identical context hashes")."""
        return context_hash(json.dumps(self.as_dict(), sort_keys=True).encode("utf-8"))


async def build_generation_request(
    pool: asyncpg.Pool, graph_name: str, calc_id: str
) -> GenerationRequest | None:
    """Assembles §9.4's own `GenerationRequest` directly from the graph -- returns `None`
    when `calc_id` does not name a live `CalculatedField`."""
    async with pool.acquire() as conn:
        calc = (await hydrate(conn, graph_name, "CalculatedField", [calc_id])).get(calc_id)
        if calc is None:
            return None

        formula_ast = calc.get("formula_ast")
        outcome = classify(formula_ast, context=await _classification_context(conn, graph_name, calc_id))

        fields, parameters, calc_deps = await _dependency_closure(conn, graph_name, calc_id)
        worksheet_ids = await _encoding_worksheets(conn, graph_name, calc_id)
        worksheets = await hydrate(conn, graph_name, "Worksheet", worksheet_ids)
        patterns = await _matching_patterns(conn, graph_name, formula_ast)

    sheet_ctx: dict[str, Any] = {
        "rows": [], "cols": [], "marks": [], "filters": [], "sort": [],
        "partitioning": "unresolved", "addressing": "unresolved",
    }
    if worksheets:
        # A calc may be encoded by more than one sheet; the first with any shelf placement
        # is used, the same "the common case is directly readable" reasoning
        # `Datasource.connection_ref` (S2.2.2) already applies to a one-of-several fact.
        sheet = next(iter(worksheets.values()))
        sheet_ctx.update(
            rows=list(sheet.get("rows_shelf") or []),
            cols=list(sheet.get("cols_shelf") or []),
            marks=list(sheet.get("marks_shelf") or []),
            filters=sheet.get("filters") or [],
            sort=sheet.get("sort") or [],
        )

    request = GenerationRequest(
        task="TRANSLATE_CALC",
        source={
            "language": "tableau_calc",
            "formula": calc.get("formula"),
            "ast": formula_ast,
            "class": outcome.class_,
            "reason": outcome.reason,
        },
        dependency_closure={
            "fields": [{"id": fid, "name": props.get("name")} for fid, props in fields.items()],
            "calculations": sorted(calc_deps),
            "parameters": [{"id": pid, "name": props.get("name")} for pid, props in parameters.items()],
        },
        sheet_ctx=sheet_ctx,
        model_ctx={
            "tables": [],
            "columns": [],
            "relationships": [],
            "existing_measures": [],
            "note": (
                "no Field→ModelTable MAPS_TO edge has ever been written by any story "
                "in this codebase (the Modeller's own S4.1.1 output never populated them) "
                "-- tables/columns/relationships are disclosed empty, not guessed at"
            ),
        },
        patterns=tuple(patterns),
        charter_excerpt={
            "note": (
                "no G1 Tolerance Charter has ever been recorded in this codebase "
                "(§4.4's charter/tolerance mechanism is not built) -- disclosed absent, "
                "not fabricated"
            ),
        },
        params=tuple(
            {"name": props.get("name"), "type": props.get("datatype"), "domain": props.get("domain")}
            for props in parameters.values()
        ),
        constraints=CONSTRAINTS,
        output_schema=OUTPUT_SCHEMA,
    )
    return request


async def _classification_context(
    conn: asyncpg.Connection, graph_name: str, calc_id: str
) -> ClassificationContext:
    param_deps = await children(conn, graph_name, [calc_id], "DEPENDS_ON", "Parameter")
    worksheet_ids = await _encoding_worksheets(conn, graph_name, calc_id)
    worksheets = await hydrate(conn, graph_name, "Worksheet", worksheet_ids)
    resolved = any(w.get("rows_shelf") or w.get("cols_shelf") for w in worksheets.values())
    return ClassificationContext(
        has_parameter_dependency=bool(param_deps.get(calc_id)),
        table_calc_addressing_resolved=resolved,
    )


async def _dependency_closure(
    conn: asyncpg.Connection, graph_name: str, calc_id: str
) -> tuple[dict[str, dict[str, Any]], dict[str, dict[str, Any]], set[str]]:
    """Every Field/Parameter reached transitively through DEPENDS_ON, and every
    CalculatedField along the way -- "dependency closure", §9.4's own second field."""
    fields: dict[str, dict[str, Any]] = {}
    parameters: dict[str, dict[str, Any]] = {}
    seen_calcs = {calc_id}
    frontier = {calc_id}

    for _ in range(MAX_CLOSURE_DEPTH):
        if not frontier:
            break
        frontier_ids = list(frontier)
        field_hits = await children(conn, graph_name, frontier_ids, "DEPENDS_ON", "Field")
        param_hits = await children(conn, graph_name, frontier_ids, "DEPENDS_ON", "Parameter")
        calc_hits = await children(conn, graph_name, frontier_ids, "DEPENDS_ON", "CalculatedField")

        field_ids = {fid for ids in field_hits.values() for fid in ids} - fields.keys()
        param_ids = {pid for ids in param_hits.values() for pid in ids} - parameters.keys()
        next_calc_ids = {cid for ids in calc_hits.values() for cid in ids} - seen_calcs

        if field_ids:
            fields.update(await hydrate(conn, graph_name, "Field", list(field_ids)))
        if param_ids:
            parameters.update(await hydrate(conn, graph_name, "Parameter", list(param_ids)))

        seen_calcs |= next_calc_ids
        frontier = next_calc_ids

    return fields, parameters, seen_calcs - {calc_id}


async def _encoding_worksheets(conn: asyncpg.Connection, graph_name: str, calc_id: str) -> list[str]:
    rows = await conn.fetch(
        f"""SELECT e.from_id AS worksheet_id
         FROM {EDGE_INDEX_TABLE} e
         JOIN {NODE_INDEX_TABLE} n ON n.id = e.from_id AND n.kind = 'node'
          AND n.graph = $1 AND n.label = 'Worksheet' AND n.retired_at IS NULL
         WHERE e.graph = $1 AND e.label = 'ENCODES' AND e.to_id = $2 AND e.retired_at IS NULL""",
        graph_name, calc_id,
    )
    return [row["worksheet_id"] for row in rows]


async def _matching_patterns(
    conn: asyncpg.Connection, graph_name: str, formula_ast: Any
) -> list[dict[str, Any]]:
    """§9.4's own "matching patterns" field, and §4.1.3's "the Pattern records whose
    source_signature matches its AST shape" -- a real query, real data since story S5.5.1
    (F5.5) started writing `Pattern` nodes. A C3 field whose shape an ACTIVE pattern
    already covers never reaches this function at all: `generate_c3_field` re-evaluates it
    to C2 and applies the pattern deterministically before `build_generation_request` is
    ever called (`patterns.apply_active_pattern`, "ahead of any model call") -- so what
    this still surfaces to a model, for a genuine C3, is CANDIDATE evidence the model may
    find useful, never something that should have skipped the model entirely."""
    rows = await conn.fetch(
        f"""SELECT id FROM {NODE_INDEX_TABLE}
         WHERE graph = $1 AND kind = 'node' AND label = 'Pattern' AND retired_at IS NULL""",
        graph_name,
    )
    if not rows:
        return []
    shape = ast_shape(formula_ast) if isinstance(formula_ast, dict) else None
    if shape is None:
        return []
    patterns = await hydrate(conn, graph_name, "Pattern", [row["id"] for row in rows])
    return [
        {"id": pid, "name": props.get("name"), "target_template": props.get("target_template")}
        for pid, props in patterns.items()
        if signature_matches(props.get("source_signature"), shape=shape, adapter="tableau")
    ]


# --------------------------------------------------------------------------- the caller


class FixtureModelCaller:
    """A `gateway.ModelCaller` that never calls a real model: every request is honestly
    declined with `NOT_EXPRESSIBLE`, the identical discipline `FixtureTargetAdapter.
    smoke_query` (S4.3.1) already set for a capability this platform cannot yet provide
    for real. Story S5.3.2 wired a real `AnthropicModelCaller` (`gateway.py`) as the
    deployed default; this stays for tests and for a deployment with no provider
    configured at all -- registering it under a gateway would never make it routable
    (it always fails its own eval set), so it is deliberately not part of `build_gateway`'s
    own provider map."""

    provider = "none"
    model = "none"

    async def generate(
        self, request: SupportsAsDict, *, previous_error: str | None
    ) -> RawModelResponse:
        raw: dict[str, Any] = {
            "dax": NOT_EXPRESSIBLE,
            "m": None,
            "assumptions": [],
            "confidence": 0.0,
            "notes": "fixture caller -- no real model was called",
        }
        return RawModelResponse(
            raw=raw,
            gateway_request_id=f"fixture_{new_ulid()}",
            provider=self.provider,
            model=self.model,
            prompt_hash=context_hash(json.dumps(request.as_dict(), sort_keys=True).encode("utf-8")),
            temperature=0.0,
            tokens_in=0,
            tokens_out=0,
        )


# --------------------------------------------------------------------- the transpile_c3 eval set


def _eval_request(*, name: str, formula: str, formula_ast: Mapping[str, Any]) -> GenerationRequest:
    """One real, minimal `GenerationRequest` for the eval corpus below -- the same shape
    `build_generation_request` produces, without needing a live graph to source it from (an
    eval case is a fixed, checked-in fact, the same footing `rules.py`'s own `GoldenCase`
    already gives a golden-corpus entry)."""
    return GenerationRequest(
        task="TRANSLATE_CALC",
        source={"language": "tableau_calc", "formula": formula, "ast": dict(formula_ast), "class": "C3", "reason": name},
        dependency_closure={"fields": [], "calculations": [], "parameters": []},
        sheet_ctx={"rows": [], "cols": [], "marks": [], "filters": [], "sort": [], "partitioning": "unresolved", "addressing": "unresolved"},
        model_ctx={"tables": [], "columns": [], "relationships": [], "existing_measures": [], "note": "eval corpus -- no live graph"},
        patterns=(),
        charter_excerpt={"note": "eval corpus -- no live graph"},
        params=(),
        constraints=CONSTRAINTS,
        output_schema=OUTPUT_SCHEMA,
    )


def _ref(name: str) -> dict[str, Any]:
    return {"kind": "REFERENCE", "name": name, "value": None, "children": [], "detail": []}


def _aggregate(name: str, *children: dict[str, Any]) -> dict[str, Any]:
    return {"kind": "AGGREGATE", "name": name, "value": None, "children": list(children), "detail": [["family", "aggregate"]]}


def _window(name: str, family: str, *children: dict[str, Any], addressing: str = "unresolved") -> dict[str, Any]:
    return {
        "kind": "WINDOW", "name": name, "value": None, "children": list(children),
        "detail": [["family", family], ["addressing", addressing], ["partitioning", "unresolved"]],
    }


def _grade_first_pass(response: RawModelResponse) -> tuple[bool, str]:
    """"First-pass proof" for this eval set (see the module docstring's own disclosure):
    does one, unretried attempt pass rung 1 (schema) and rung 2 (parse) -- reusing the
    exact same real checks `_run_ladder` runs, not a re-implementation of them."""
    try:
        parsed = ModelResponseSchema.model_validate(dict(response.raw))
    except ValidationError as exc:
        return False, f"schema: {exc}"
    if parsed.dax == NOT_EXPRESSIBLE:
        return False, f"declined: {parsed.notes}"
    parse_error = dax_sanity_check(parsed.dax)
    if parse_error is not None:
        return False, f"parse: {parse_error}"
    return True, "schema + parse passed on the first attempt"


#: A real, fixed, checked-in corpus of five C3 table-calc idioms (the same "at least a
#: handful, run for real, checked into version control" shape `rules.py`'s own
#: `RULES[*].golden_cases` already established) -- table calcs specifically, since they are
#: C3's own clearest idiom (`classify.py`'s "no rule matches or context is required"); a
#: second, broader corpus covering LOD/parameter-dependent idioms is a natural extension,
#: not built here.
TRANSPILE_C3_EVAL_CASES: tuple[EvalCase, ...] = (
    EvalCase(
        name="running_sum_unresolved",
        request=_eval_request(
            name="running_sum_unresolved", formula="RUNNING_SUM(SUM([Notional]))",
            formula_ast=_window("RUNNING_SUM", "table_calc_simple", _aggregate("SUM", _ref("Notional"))),
        ),
        grade=_grade_first_pass,
    ),
    EvalCase(
        name="running_avg_unresolved",
        request=_eval_request(
            name="running_avg_unresolved", formula="RUNNING_AVG(SUM([Revenue]))",
            formula_ast=_window("RUNNING_AVG", "table_calc_simple", _aggregate("SUM", _ref("Revenue"))),
        ),
        grade=_grade_first_pass,
    ),
    EvalCase(
        name="rank_resolved",
        request=_eval_request(
            name="rank_resolved", formula="RANK(SUM([Notional]))",
            formula_ast=_window("RANK", "table_calc_complex", _aggregate("SUM", _ref("Notional")), addressing="resolved"),
        ),
        grade=_grade_first_pass,
    ),
    EvalCase(
        name="window_sum_unresolved",
        request=_eval_request(
            name="window_sum_unresolved", formula="WINDOW_SUM(SUM([Margin]))",
            formula_ast=_window("WINDOW_SUM", "table_calc_simple", _aggregate("SUM", _ref("Margin"))),
        ),
        grade=_grade_first_pass,
    ),
    EvalCase(
        name="index_resolved",
        request=_eval_request(
            name="index_resolved", formula="INDEX()",
            formula_ast=_window("INDEX", "table_calc_complex", addressing="resolved"),
        ),
        grade=_grade_first_pass,
    ),
)


async def run_transpile_c3_eval(caller: ModelCaller) -> EvalReport:
    """Runs `caller` for real against `TRANSPILE_C3_EVAL_CASES` and grades every response.
    Does not record anything -- `gateway.GatewayPolicyStore.record_eval` is the caller's own
    next step (the API route does both, so a run and its recorded verdict are always one
    atomic action from an operator's point of view)."""
    return await run_eval_set(caller, task_class=TRANSPILE_C3, cases=TRANSPILE_C3_EVAL_CASES)


# ---------------------------------------------------------------------------- the ladder


@dataclass(frozen=True, slots=True)
class LadderAttempt:
    attempt: int
    raw_response: Mapping[str, Any]
    schema_ok: bool
    schema_error: str | None
    not_expressible: bool
    not_expressible_reason: str | None
    parse_ok: bool
    parse_error: str | None
    compile_ok: bool
    compile_detail: str
    proof_ok: bool
    proof_detail: str
    dax: str | None
    gateway_request_id: str
    provider: str
    model: str
    prompt_hash: str
    temperature: float
    tokens_in: int
    tokens_out: int
    confidence: float | None = None
    gateway_error: str | None = None
    """§5.5: "routes by task class and tenant policy" -- set when the gateway itself had
    no routable provider to call at all (story S5.3.2's own `GatewayRoutingError`), a
    different, earlier failure than a model responding badly. `None` on every other kind
    of attempt."""

    def as_dict(self) -> dict[str, Any]:
        return {
            "attempt": self.attempt,
            "raw_response": dict(self.raw_response),
            "gateway_error": self.gateway_error,
            "schema": {"ok": self.schema_ok, "error": self.schema_error},
            "not_expressible": self.not_expressible,
            "not_expressible_reason": self.not_expressible_reason,
            "parse": {"ok": self.parse_ok, "error": self.parse_error},
            "compile": {"ok": self.compile_ok, "detail": self.compile_detail},
            "proof": {"ok": self.proof_ok, "detail": self.proof_detail},
            "dax": self.dax,
            "gateway_request_id": self.gateway_request_id,
            "provider": self.provider,
            "model": self.model,
            "prompt_hash": self.prompt_hash,
            "temperature": self.temperature,
            "tokens_in": self.tokens_in,
            "tokens_out": self.tokens_out,
            "confidence": self.confidence,
        }


@dataclass(frozen=True, slots=True)
class GenerationOutcome:
    calculated_field_id: str
    ok: bool
    measure_id: str | None
    exception_case_id: str | None
    attempts: tuple[LadderAttempt, ...]
    reason: str
    task_class: str = TRANSPILE_C3
    """Which routing destination actually served this call — `TRANSPILE_C3` (reasoning
    tier) unless S5.3.3's own calibration floor had already been crossed, in which case
    `TRANSPILE_C3_SMALL_MODEL`. Left at the reasoning-tier default on the two early-return
    outcomes (no such field; not C3) that never reach the ladder at all."""
    pattern_id: str | None = None
    """Story S5.5.1: the real `Pattern` node this call was actually served by — set only
    when an ACTIVE pattern's own deterministic application produced `measure_id`, never a
    model call. `None` for a genuine model-served outcome (`task_class` names what served
    it instead) and for either early-return outcome."""

    def as_dict(self) -> dict[str, Any]:
        return {
            "calculated_field_id": self.calculated_field_id,
            "ok": self.ok,
            "measure_id": self.measure_id,
            "exception_case_id": self.exception_case_id,
            "attempts": [a.as_dict() for a in self.attempts],
            "reason": self.reason,
            "task_class": self.task_class,
            "pattern_id": self.pattern_id,
        }


async def _run_ladder(
    request: GenerationRequest, *, gateway: Gateway, task_class: str = TRANSPILE_C3
) -> tuple[tuple[LadderAttempt, ...], LadderAttempt | None]:
    """Runs the request through the ladder, up to `MAX_ATTEMPTS` times, calling
    `gateway.generate(task_class=..., ...)` -- never a provider by name (S5.3.2's own AC).
    `task_class` defaults to `TRANSPILE_C3` (the reasoning tier); `generate_c3_field` passes
    `TRANSPILE_C3_SMALL_MODEL` instead when S5.3.3's own calibration floor has been crossed.
    Returns every attempt made, and the attempt that succeeded (parsed) if one did."""
    attempts: list[LadderAttempt] = []
    previous_error: str | None = None

    for attempt_number in range(1, MAX_ATTEMPTS + 1):
        try:
            response = await gateway.generate(
                task_class=task_class, request=request, previous_error=previous_error
            )
        except GatewayRoutingError as exc:
            attempts.append(
                LadderAttempt(
                    attempt=attempt_number, raw_response={},
                    schema_ok=False, schema_error=None,
                    not_expressible=False, not_expressible_reason=None,
                    parse_ok=False, parse_error=None,
                    compile_ok=False, compile_detail="not reached",
                    proof_ok=False, proof_detail="not reached",
                    dax=None, gateway_request_id="", provider="", model="",
                    prompt_hash="", temperature=0.0, tokens_in=0, tokens_out=0,
                    gateway_error=str(exc),
                )
            )
            # No routable provider won't become one within a single ladder run -- not
            # retried, the same "the fault isn't this attempt's" footing a schema
            # failure already has.
            break

        try:
            parsed = ModelResponseSchema.model_validate(dict(response.raw))
        except ValidationError as exc:
            attempts.append(
                LadderAttempt(
                    attempt=attempt_number, raw_response=response.raw,
                    schema_ok=False, schema_error=str(exc),
                    not_expressible=False, not_expressible_reason=None,
                    parse_ok=False, parse_error=None,
                    compile_ok=False, compile_detail="not reached",
                    proof_ok=False, proof_detail="not reached",
                    dax=None, gateway_request_id=response.gateway_request_id,
                    provider=response.provider, model=response.model,
                    prompt_hash=response.prompt_hash, temperature=response.temperature,
                    tokens_in=response.tokens_in, tokens_out=response.tokens_out,
                )
            )
            # §16.1: "Hard failure; logged; no retry on schema -- the prompt contract is at
            # fault", not the calculation.
            break

        if parsed.dax == NOT_EXPRESSIBLE:
            attempts.append(
                LadderAttempt(
                    attempt=attempt_number, raw_response=response.raw,
                    schema_ok=True, schema_error=None,
                    not_expressible=True, not_expressible_reason=parsed.notes,
                    parse_ok=False, parse_error=None,
                    compile_ok=False, compile_detail="not reached",
                    proof_ok=False, proof_detail="not reached",
                    dax=None, gateway_request_id=response.gateway_request_id,
                    provider=response.provider, model=response.model,
                    prompt_hash=response.prompt_hash, temperature=response.temperature,
                    tokens_in=response.tokens_in, tokens_out=response.tokens_out,
                    confidence=parsed.confidence,
                )
            )
            # §9.4: "A NOT_EXPRESSIBLE response ... produces a Class 4 flag" -- immediate,
            # not retried.
            break

        parse_error = dax_sanity_check(parsed.dax)
        if parse_error is not None:
            attempts.append(
                LadderAttempt(
                    attempt=attempt_number, raw_response=response.raw,
                    schema_ok=True, schema_error=None,
                    not_expressible=False, not_expressible_reason=None,
                    parse_ok=False, parse_error=parse_error,
                    compile_ok=False, compile_detail="not reached",
                    proof_ok=False, proof_detail="not reached",
                    dax=parsed.dax, gateway_request_id=response.gateway_request_id,
                    provider=response.provider, model=response.model,
                    prompt_hash=response.prompt_hash, temperature=response.temperature,
                    tokens_in=response.tokens_in, tokens_out=response.tokens_out,
                    confidence=parsed.confidence,
                )
            )
            previous_error = f"parse error: {parse_error}"
            continue  # one regeneration, per §16.1's own rung-2 row

        # Rungs 3 (compile) and 4 (proof): disclosed, unconditional passes -- see the
        # module docstring's own "What this module is not" section.
        success = LadderAttempt(
            attempt=attempt_number, raw_response=response.raw,
            schema_ok=True, schema_error=None,
            not_expressible=False, not_expressible_reason=None,
            parse_ok=True, parse_error=None,
            compile_ok=True,
            compile_detail="no live Fabric dev workspace exists to compile against (E11) -- disclosed pass",
            proof_ok=True,
            proof_detail="no Arbiter (E7) exists to grant a real parity verdict -- disclosed pass",
            dax=parsed.dax, gateway_request_id=response.gateway_request_id,
            provider=response.provider, model=response.model,
            prompt_hash=response.prompt_hash, temperature=response.temperature,
            tokens_in=response.tokens_in, tokens_out=response.tokens_out,
            confidence=parsed.confidence,
        )
        attempts.append(success)
        return tuple(attempts), success

    return tuple(attempts), None


# ------------------------------------------------------------------------- estate-wide pass

_NODE_SERVER_MANAGED = frozenset(p.name for p in BASE_NODE_PROPERTIES if p.server_managed) | {
    "id",
    "side",
}


def _writable_node_properties(properties: Mapping[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in properties.items() if k not in _NODE_SERVER_MANAGED}


class GenerationEngine:
    """The pool/graph/writer/provenance-store a generation route needs -- the same small
    wrapper shape `classify.py`'s `ClassificationEngine`/`rules.py`'s `RulesEngine` already
    established."""

    def __init__(
        self,
        pool: asyncpg.Pool,
        *,
        graph_name: str,
        writer: GraphWriter,
        provenance_store: ProvenanceStore,
        gateway: Gateway | None = None,
        calibration: CalibrationStore | None = None,
    ) -> None:
        self._pool = pool
        self._graph = graph_name
        self._writer = writer
        self._provenance = provenance_store
        self._gateway = gateway or null_gateway()
        self._calibration = calibration or NullCalibrationStore()

    @property
    def pool(self) -> asyncpg.Pool:
        return self._pool

    @property
    def graph_name(self) -> str:
        return self._graph

    @property
    def writer(self) -> GraphWriter:
        return self._writer

    @property
    def provenance(self) -> ProvenanceStore:
        return self._provenance

    @property
    def gateway(self) -> Gateway:
        return self._gateway

    @property
    def calibration(self) -> CalibrationStore:
        return self._calibration


async def generate_c3_field(
    pool: asyncpg.Pool,
    graph_name: str,
    writer: GraphWriter,
    provenance_store: ProvenanceStore,
    calc_id: str,
    *,
    gateway: Gateway,
    calibration: CalibrationStore | None = None,
    principal: Principal,
) -> GenerationOutcome:
    """Runs one C3 `CalculatedField` through §9.4/§16.1: build the request, run the ladder
    (up to `MAX_ATTEMPTS`), and on success write a real `Measure`/`MAPS_TO`/
    `ProvenanceRecord` (mode `GENERATED_PROVED`); on exhaustion or `NOT_EXPRESSIBLE`, write
    a real `ExceptionCase` with every attempt attached (this story's own acceptance
    criteria, verbatim). Story S5.3.3: before running the ladder, checks whether
    `TRANSPILE_C3`'s own calibration has fallen below its floor and, if so, runs it against
    `TRANSPILE_C3_SMALL_MODEL` instead (§16.3's own "routed ... rather than trusted") — and
    afterwards records a real calibration observation for every attempt that declared a
    confidence, so later calls have real history to check against.

    Story S5.5.1: before any of that, checks whether an ACTIVE `Pattern` already covers
    this AST's own shape. If one does, it is applied deterministically
    (`patterns.apply_active_pattern`) and the model is never called at all — the field's
    own `class` is re-evaluated to C2 with a real `pattern_ref`, the AC's own bullet 3,
    verbatim. A successful model-served generation instead generalises into a real
    `Pattern` candidate (`patterns.generalise_from_proof`, bullet 1); a failed one records
    a proof failure against any existing candidate/active pattern for its shape, so "zero
    failures" (bullet 2's own promotion gate) is a real, checked fact and not vacuously
    true."""
    calibration_store = calibration or NullCalibrationStore()

    async with pool.acquire() as conn:
        calc = (await hydrate(conn, graph_name, "CalculatedField", [calc_id])).get(calc_id)
    if calc is None:
        return GenerationOutcome(calc_id, False, None, None, (), "no such CalculatedField")

    classification = classify(
        calc.get("formula_ast"),
        context=await _classification_context_from_pool(pool, graph_name, calc_id),
    )
    if classification.class_ != "C3":
        return GenerationOutcome(
            calc_id, False, None, None, (),
            f"not a Class 3 calculation (classified {classification.class_}); this pipeline is C3-only",
        )

    formula_ast = calc.get("formula_ast")
    existing_pattern = await find_matching_pattern(pool, graph_name, formula_ast)
    if existing_pattern is not None and existing_pattern.promotion_state == "ACTIVE":
        async with pool.acquire() as conn:
            graph_version = await _current_version(conn, graph_name)
        measure_id = await apply_active_pattern(
            pool, graph_name, writer, provenance_store,
            calc_id=calc_id, calc_properties=calc, pattern=existing_pattern,
            graph_version=graph_version, principal=principal,
        )
        if measure_id is not None:
            return GenerationOutcome(
                calc_id, True, measure_id, None, (),
                "applied an ACTIVE Pattern deterministically -- no model was called (§9.3)",
                pattern_id=existing_pattern.pattern_id,
            )
        # The pattern's own deterministic render failed even the structural sanity check
        # (recorded as a failure observation by apply_active_pattern itself) -- fall
        # through to the normal model-call path rather than blocking this field on one
        # pattern's own hiccup.

    request = await build_generation_request(pool, graph_name, calc_id)
    assert request is not None  # calc existed above; nothing retired it in between

    task_class = (
        TRANSPILE_C3_SMALL_MODEL
        if await calibration_store.is_below_floor(TRANSPILE_C3)
        else TRANSPILE_C3
    )
    attempts, success = await _run_ladder(request, gateway=gateway, task_class=task_class)

    # A real observation for every attempt that got far enough to declare a confidence --
    # under TRANSPILE_C3's own identity always: a rerouted call never reaches a real model
    # (no ModelCaller is ever registered under TRANSPILE_C3_SMALL_MODEL), so it never has a
    # confidence to record here regardless of which task_class was actually asked for.
    for attempt in attempts:
        if attempt.confidence is not None:
            await calibration_store.record(
                task_class=TRANSPILE_C3, agent=_AGENT, model=attempt.model, provider=attempt.provider,
                confidence=attempt.confidence, observed_pass=attempt.parse_ok, created_by=principal.value,
            )

    if success is not None:
        measure_id = await _write_measure(
            pool, graph_name, writer, provenance_store, calc_id, calc, success, principal=principal,
        )
        pattern_id = await generalise_from_proof(
            pool, graph_name, writer,
            calc_id=calc_id, formula_ast=formula_ast, dax=success.dax or "", class_="C3",
            principal=principal,
        )
        return GenerationOutcome(
            calc_id, True, measure_id, None, attempts,
            "generated and validated through rung 4 (compile/proof are disclosed passes; see module docstring)",
            task_class=task_class, pattern_id=pattern_id,
        )

    exception_case_id = await _write_exception_case(
        pool, graph_name, writer, calc_id, attempts, principal=principal,
    )
    if existing_pattern is not None:
        # A shape an existing candidate/active pattern already covers just failed the
        # normal model-call path too -- real evidence against it, so bullet 2's own "zero
        # failures" promotion gate is a fact this platform checked, not an assumption.
        await record_observation(
            pool, graph_name, pattern_id=existing_pattern.pattern_id, calc_id=calc_id,
            observed_pass=False, source="GENERATED_PROVED", created_by=principal.value,
        )
    last = attempts[-1] if attempts else None
    reason = (
        last.gateway_error if last and last.gateway_error
        else "model response failed schema validation" if last and not last.schema_ok
        else "model declined: NOT_EXPRESSIBLE" if last and last.not_expressible
        else f"exhausted {MAX_ATTEMPTS} attempts without a parseable candidate"
    )
    return GenerationOutcome(calc_id, False, None, exception_case_id, attempts, reason, task_class=task_class)


async def _classification_context_from_pool(
    pool: asyncpg.Pool, graph_name: str, calc_id: str
) -> ClassificationContext:
    async with pool.acquire() as conn:
        return await _classification_context(conn, graph_name, calc_id)


async def _write_measure(
    pool: asyncpg.Pool,
    graph_name: str,
    writer: GraphWriter,
    provenance_store: ProvenanceStore,
    calc_id: str,
    calc: Mapping[str, Any],
    success: LadderAttempt,
    *,
    principal: Principal,
) -> str:
    measure_id = new_ulid()
    provenance_id = f"prov_{new_ulid()}"
    request_hash = success.raw_response  # captured for the record's own context_hash below

    async with pool.acquire() as conn:
        graph_version = await _current_version(conn, graph_name)

    # No `pattern_ref` on either the Measure or the MAPS_TO edge: a GENERATED_PROVED
    # artefact was not produced by a rule or a Pattern (both of which mean determinism a
    # generated candidate does not have) -- the same "omit an absent optional property
    # rather than write it as an explicit null" convention `rules.py`'s own C1/C2 writes
    # already follow.
    writer_props = {
        "name": str(calc.get("name") or calc_id),
        "dax": success.dax,
        "source_calc_ref": calc_id,
        "class": "C3",
        "provenance_ref": provenance_id,
        "validation_state": (
            "rung 4 (disclosed): schema PASS, parse PASS, compile PASS (disclosed -- no "
            "live Fabric dev workspace, E11), proof PASS (disclosed -- no Arbiter, E7)"
        ),
    }
    await writer.write_nodes(
        [NodeWrite(type="Measure", id=measure_id, properties=writer_props)], principal=principal
    )
    await writer.write_edge(
        EdgeWrite(
            type="MAPS_TO", from_id=calc_id, to_id=measure_id,
            properties={"class": "C3"},
        ),
        principal=principal,
    )

    record = new_record(
        id=provenance_id,
        artefact_kind="MEASURE",
        artefact_ref=measure_id,
        artefact_content_hash=context_hash(str(success.dax).encode("utf-8")),
        agent=_AGENT,
        agent_version=_AGENT_VERSION,
        mode=AgentMode.GENERATED_PROVED,
        contract=ContractName.TRANSPILER_CALC,
        subject_id=calc_id,
        context_hash=context_hash(json.dumps(dict(request_hash), sort_keys=True).encode("utf-8")),
        graph_version=graph_version,
        model=success.model,
        prompt_hash=success.prompt_hash,
        tokens_in=success.tokens_in,
        tokens_out=success.tokens_out,
        confidence=success.confidence,
        provider=success.provider,
        gateway_request_id=success.gateway_request_id,
        temperature=success.temperature,
        created_by=principal.value,
    )
    await provenance_store.record(record)
    return measure_id


async def _write_exception_case(
    pool: asyncpg.Pool,
    graph_name: str,
    writer: GraphWriter,
    calc_id: str,
    attempts: tuple[LadderAttempt, ...],
    *,
    principal: Principal,
) -> str:
    """§11.3: "Each ExceptionCase carries the full evidence bundle ... and the model's
    diagnosis where one was made." No Migration Unit exists to name in `mu_ref` (E3/E7's
    own territory, the identical disclosed-gap `regression_status`/`UngatedPromotions`
    already carry) -- the calculated field id stands in, honestly labelled.

    `class` uses `_FAILURE_CLASSES`' own `UNKNOWN` member: that taxonomy (§11.1) is for
    *parity* failures the Mender diagnoses after a real proof attempt, a different moment
    from this story's own pre-proof generation failures -- a real, disclosed mismatch, not
    a false claim to a category that fits.
    """
    case_id = new_ulid()
    evidence = {"calculated_field_id": calc_id, "attempts": [a.as_dict() for a in attempts]}
    await writer.write_nodes(
        [
            NodeWrite(
                type="ExceptionCase",
                id=case_id,
                properties={
                    "mu_ref": f"calc:{calc_id}",
                    "class": "UNKNOWN",
                    "evidence_ref": context_hash(json.dumps(evidence, sort_keys=True).encode("utf-8")),
                    "state": "OPEN",
                },
            )
        ],
        principal=principal,
    )
    return case_id


async def _current_version(conn: asyncpg.Connection, graph_name: str) -> int:
    row = await conn.fetchrow(
        f"SELECT seq FROM {EVENT_TABLE} WHERE graph = $1 ORDER BY seq DESC LIMIT 1", graph_name
    )
    return int(row["seq"]) if row else 0


__all__ = [
    "CONSTRAINTS",
    "MAX_ATTEMPTS",
    "MAX_CLOSURE_DEPTH",
    "NOT_EXPRESSIBLE",
    "OUTPUT_SCHEMA",
    "TRANSPILE_C3_EVAL_CASES",
    "FixtureModelCaller",
    "GenerationEngine",
    "GenerationOutcome",
    "GenerationRequest",
    "LadderAttempt",
    "ModelCaller",
    "ModelResponseSchema",
    "RawModelResponse",
    "build_generation_request",
    "generate_c3_field",
    "run_transpile_c3_eval",
]
