"""C3 generation's own API — story S5.3.1.

    "C3 calculations generated by a model with the context contract and validated up the
    ladder before proof, so that a model output can never reach the client repository
    without passing execution."

Reading a generated context/outcome is open to any Artizent role, the same posture every
other Transpiler read in this API already has; triggering generation is the parity
engineer's (`ParityEngineerDep`), the persona this story's own acceptance criteria names —
the same role S5.1.1's classifier already drives.
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Path, Request

from ..errors import ElementNotFoundError, InvalidRequestError
from ..generation import GenerationEngine, build_generation_request, generate_c3_field
from .deps import ArtizentDep, ParityEngineerDep, PrincipalDep

router = APIRouter()

_CALC_ID = Path(min_length=5, max_length=64, description="ULID of the CalculatedField.")


def _engine(request: Request) -> GenerationEngine:
    engine: GenerationEngine | None = getattr(request.app.state, "generation_engine", None)
    if engine is None:
        raise InvalidRequestError("C3 generation is not available on this deployment")
    return engine


@router.get(
    "/v1/calculations/{calc_id}:generation-request",
    tags=["generation"],
    summary="The §9.4 GenerationRequest a C3 field would be sent with, without calling the model",
)
async def get_generation_request(
    request: Request, principal: PrincipalDep, roles: ArtizentDep, calc_id: str = _CALC_ID
) -> dict[str, Any]:
    engine = _engine(request)
    generation_request = await build_generation_request(engine.pool, engine.graph_name, calc_id)
    if generation_request is None:
        raise ElementNotFoundError(f"no CalculatedField '{calc_id}'")
    return generation_request.as_dict()


@router.post(
    "/v1/calculations/{calc_id}:generate",
    tags=["generation"],
    summary="Run one Class 3 field through the validation ladder (§9.4/§16.1)",
)
async def generate(
    request: Request, principal: PrincipalDep, roles: ParityEngineerDep, calc_id: str = _CALC_ID
) -> dict[str, Any]:
    engine = _engine(request)
    outcome = await generate_c3_field(
        engine.pool, engine.graph_name, engine.writer, engine.provenance, calc_id,
        gateway=engine.gateway, principal=principal,
    )
    return outcome.as_dict()


__all__ = ["router"]
